
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/alexa/Documents/Cmake/cmake-3.26.4-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.22631 - AMD64
...
